version: '3.8'
services:
  client-backend:
    image: hakaton:v8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8097:8097"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8097
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/postgres

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
