version: '3.8'
services:
  client-backend:
    image: ld40fkffbxhl/hakaton:v8
    ports:
      - "8097:8097"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8097
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/postgres

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  grafana:
    image: ld40fkffbxhl/grafana:v1
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    user: "0"
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    user: "0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus
volumes:
  db-data:
networks:
  monitoring:
