export enum Role {
    ENROLLEE = "ENROLLEE",
    TEACHER = "TEACHER",
    STUDENT = "STUDENT",
    ADMIN = "ADMIN",
    SELLECTION_COMMITE = "SELLECTION_COMMITE",
    SUPERVISOR = "SUPERVISOR",
    MANAGER = "MANAGER",
}
