version: '3.8'
services:
  client-backend:
    image: hakaton:v7
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8097:8097"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8097
      - SPRING_DATASOURCE_URL=jdbc:postgresql://CommercialEdu?currentSchema=public

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
  pgadmin-data: